// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85PQCrhty9FyXUWEP_OxCHJlJLrbkbxo',
    appId: '1:652864415863:web:3ae3b12271da33e557fe72',
    messagingSenderId: '652864415863',
    projectId: 'mynotes-flutter-project-b77a5',
    authDomain: 'mynotes-flutter-project-b77a5.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-b77a5.appspot.com',
    measurementId: 'G-6E0P2FC3CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNAsjvMM9yKJYjlvFjMot2BPDy2Kg3Vsc',
    appId: '1:652864415863:android:40b17ce60e872bc957fe72',
    messagingSenderId: '652864415863',
    projectId: 'mynotes-flutter-project-b77a5',
    storageBucket: 'mynotes-flutter-project-b77a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp32XlVVNn-QdyqTrxcjOOrV3JU9_xlBQ',
    appId: '1:652864415863:ios:d7559947cd6753aa57fe72',
    messagingSenderId: '652864415863',
    projectId: 'mynotes-flutter-project-b77a5',
    storageBucket: 'mynotes-flutter-project-b77a5.appspot.com',
    iosClientId: '652864415863-qg22ujua2bh387sd7ggnb3lassgln6n0.apps.googleusercontent.com',
    iosBundleId: 'v.brnr.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp32XlVVNn-QdyqTrxcjOOrV3JU9_xlBQ',
    appId: '1:652864415863:ios:d7559947cd6753aa57fe72',
    messagingSenderId: '652864415863',
    projectId: 'mynotes-flutter-project-b77a5',
    storageBucket: 'mynotes-flutter-project-b77a5.appspot.com',
    iosClientId: '652864415863-qg22ujua2bh387sd7ggnb3lassgln6n0.apps.googleusercontent.com',
    iosBundleId: 'v.brnr.mynotes',
  );
}
